CREATE TABLE TEACHER(
  id INTEGER NOT NULL AUTO_INCREMENT,
  name NOT NULL,
  age NUMBER(3) NOT NULL, -- NUMERIC(3) means INTEGER
  nationality VARCHAR(2) NOT NULL,
  membership VARCHAR(1) NOT NULL
);